# Generated by Django 6.0 on 2026-01-01 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shortDesc', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='blog/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='client/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='companypage/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactFormHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Unique key for frontend (e.g. contact_form_home_page)', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subjectMessage', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. phone, email, map, website', max_length=50, unique=True)),
                ('requires_url', models.BooleanField(default=True, help_text='Uncheck if this type does NOT need URL (e.g. phone/email)')),
                ('lucideicon', models.CharField(blank=True, help_text='Lucide icon name (e.g. phone, email, map-pin)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shortDesc', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='event/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shortDesc', models.CharField(blank=True, max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Header_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='header/')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Unique key for frontend (e.g. who_we_are, what_we_build)', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('url', models.URLField(blank=True, help_text='Add the url of the page to redirect to when the brief is clicked', null=True)),
                ('bg_video', models.FileField(blank=True, null=True, upload_to='homepage/brief/')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='homepage/brief/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage/hero/')),
                ('button_text', models.CharField(blank=True, max_length=200)),
                ('button_url', models.URLField(blank=True)),
                ('button_target', models.CharField(choices=[('_self', 'Same Tab'), ('_blank', 'New Tab')], default='_self', max_length=20)),
                ('button_color', models.CharField(blank=True, max_length=50)),
                ('button_background_color', models.CharField(blank=True, max_length=50)),
                ('button_border_color', models.CharField(blank=True, max_length=50)),
                ('button_border_radius', models.CharField(blank=True, max_length=20)),
                ('button_border_width', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='key_feature/')),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shortDesc', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project/')),
                ('url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shortDesc', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='publication/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('logo_icon', models.CharField(blank=True, help_text='Lucide icon name (e.g. code, cloud, brain)', max_length=50)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='services/banner/')),
                ('banner_video', models.FileField(blank=True, null=True, upload_to='services/banner/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('shortDesc', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='testimonial/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='text_for_brief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Example: homepage_brief_title', max_length=100, unique=True)),
                ('title', models.CharField(default='Brief about us', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='contactdetails/')),
                ('url', models.URLField(blank=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.contacttype')),
            ],
        ),
    ]
