# Generated by Django 6.0 on 2026-01-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_democategory_alter_keyfeature_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='bg_video',
            field=models.FileField(blank=True, null=True, upload_to='services/bg_video/'),
        ),
    ]
