# Generated by Django 6.0 on 2026-01-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_bg_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebrief',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/brief_banner/'),
        ),
    ]
