# Generated by Django 6.0 on 2026-01-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='bg_video',
            field=models.FileField(blank=True, help_text='Looping video for the service card background.', null=True, upload_to='services/bg_video/'),
        ),
    ]
