# Generated by Django 6.0 on 2026-01-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_service_bg_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='advantage_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='advantage_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='advantage_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of display, lower comes first'),
        ),
        migrations.AddField(
            model_name='service',
            name='technical_specs',
            field=models.TextField(blank=True, help_text='Technical details or tech stack'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Main content for the detail page'),
        ),
    ]
